# Generated by Django 4.1.7 on 2023-03-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_id_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='user_files/'),
        ),
    ]
