# Generated by Django 4.1.7 on 2023-03-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_id_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('profession', 'Professional')], default='student', max_length=255),
            preserve_default=False,
        ),
    ]
