# Generated by Django 4.1.7 on 2023-03-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
